<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GradBook.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="wwwroot\NewFolder\mohammad.JPG" />
    <Content Remove="wwwroot\uploads\mohammad.JPG" />
  </ItemGroup>
  <ItemGroup>
    <None Include="wwwroot\NewFolder\mohammad.JPG" />
    <None Include="wwwroot\uploads\mohammad.JPG" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GradBook.Application\GradBook.Application.csproj" />
    <ProjectReference Include="..\GradBook.Infrastructure\GradBook.Infrastructure.csproj" />
  </ItemGroup>
</Project>
